# This workflow will build a Java project with Maven

name: External PR

on:
  pull_request:

env:
  # Base for the PR
  BASE_REPO: ${{ github.event.pull_request.base.repo.clone_url }}

  # Repository of PR
  PR_HEAD_REPO: ${{ github.event.pull_request.head.repo.clone_url }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      if: ${{ env.BASE_REPO != env.PR_HEAD_REPO }}
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      if: ${{ env.BASE_REPO != env.PR_HEAD_REPO }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
      if: ${{ env.BASE_REPO != env.PR_HEAD_REPO }}
    - name: Build with Maven
      run: mvn -f io.github.lorenzobettini.example/pom.xml verify
      if: ${{ env.BASE_REPO != env.PR_HEAD_REPO }}
